{-# LANGUAGE DeriveDataTypeable, RecordWildCards #-}

import Test.HUnit ((@=?), assertBool, runTestTT, Test(..))
import Text.Printf (printf)
import System.Console.CmdArgs
import Data.Time (getCurrentTime, diffUTCTime)

-- Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
-- Triangle     Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
-- Pentagonal   Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
-- Hexagonal    Hn=n(2n−1)      1, 6, 15, 28, 45, ...
-- It can be verified that T285 = P165 = H143 = 40755.
-- Find the next triangle number that is also pentagonal and hexagonal.

data EulerArgs = 
    Euler 
    | Triangle{ limit::Int }
    | Pentagonal{ limit::Int }
    | Hexagonal{ limit::Int }
    | AdHoc{ limit::Int }
    | UnitTest
    deriving (Show, Data, Typeable)

problem0045 :: [Integer]
problem0045 = common [pentagonal, hexagonal, triangle]

triangle  = [ div (n*(  n+1)) 2 | n <- [1..]]
hexagonal = [ div (n*(3*n-1)) 2 | n <- [1..]]
pentagonal= [     (n*(2*n-1))   | n <- [1..]]

common :: (Ord a) => [[a]] -> [a]
common ls
    | any null ls = []
    | all ((==) x . head) ls' = x : (common $ map tail ls')
    | otherwise = common ls''
    where
        x = head $ head ls
        ls' = map (dropWhile (<x)) ls
        ls'' = map (dropWhile (<=x)) ls

commonTest = [
    [0,6,12,18] @=? common [[0..20],[0,2..20],[0,3..20]],
    [2,4,6] @=? common [[2,4,6],[1..6],[0..10]],
    [2,4,6] @=? common [[2,4,6],[1..6]],
    [2,4,6] @=? common [[2,4,6]]]

unitTests = map TestCase $
    commonTest

exec :: EulerArgs -> IO ()
exec Euler = do
    let answer = head $ drop 2 problem0045
    printf "Answer: %d\n" answer
exec AdHoc{..} = do
    mapM_ print $ take limit $ problem0045
exec UnitTest = do 
    runTestTT $ TestList unitTests
    return ()
exec Triangle{..} = do 
    mapM_ print $ take limit triangle
exec Pentagonal{..} = do 
    mapM_ print $ take limit pentagonal
exec Hexagonal{..}= do
    mapM_ print $ take limit hexagonal

main :: IO ()
main = do
    args <- cmdArgs $ modes [
        Euler,
        Triangle{ limit=10 },
        Pentagonal{ limit=10 },
        Hexagonal{ limit=10 },
        AdHoc{ limit = 4 },
        UnitTest]
    start <- getCurrentTime
    exec args
    stop <- getCurrentTime
    print $ diffUTCTime stop start
